### ISSUE TITLE
Messages

### ISSUE THREAD

**Issue by RhythmicSys** [0PandaDEV/EssentialsP#1]
Not really an issue, just didn't know where else to put it.
I wrote up these messages because I want to use the plugin, but only speak English, lol
I'm not sure if you would like them or not, but figured I'd send them in case they'd be useful

[idk the english messages or at least i think they are.txt](https://github.com/0PandaDEV/EssentialsP/files/9524396/idk.the.english.messages.or.at.least.i.think.they.are.txt)

**Comment by 0PandaDEV** [comment]
:) I just finished my translation today, but thanks I will most likely release a beta today where you can switch between english and german in the config file.

**Comment by RhythmicSys** [comment]
Okay cool!

**Comment by 0PandaDEV** [comment]
If you want to test it, I have posted the Beta release [Here](https://modrinth.com/plugin/essentialsp/version/v1.2.1)

**Comment by RhythmicSys** [comment]
Awesome :D
Couple things:
`don't exists` should be `doesn't exist` or `does not exist` 

The messages for the default homes don't seem to use the language file messages
![image](https://user-images.githubusercontent.com/45906780/189416072-f728f39d-158d-4492-bfd5-93ec5557825f.png)
![image](https://user-images.githubusercontent.com/45906780/189416098-cd8a8c2f-0d84-4146-9666-1ed3555459f8.png)

Small English spelling error in default 'feature not available' message: `feauture` should be `feature`

`"when you enter or leave the vanish"` sounds strange since 'the' is generally used before a noun, and 'vanish' is a verb. `"when you enter or leave vanish"` or `"when you enter or leave vanish mode"` would sound less strange 

![image](https://user-images.githubusercontent.com/45906780/189417544-e0a6bd25-d7f1-4df5-a6a9-e6de0074162d.png)

`Controls whether a message is considered a result to be displayed after a command` does not make any sense to me, at all

`Controls whether a message should be sent after a command` or something similar, probably.

`/fly` does not provide any command feedback

Attempting to `/heal` a player that is not online provides a `null` message rather than `invalid player` message

`invalid player` message is not pulling from language
![image](https://user-images.githubusercontent.com/45906780/189419185-74361562-9cf7-4480-8efc-cc69923438b9.png)

You cannot `/tphere` yourself but you can `/tpa` yourself 

No handling for people being stupid like me and putting letters in speed setting
```console
[11:31:50 INFO]: _Rhythmic issued server command: /speed 1.3000aaaaaaa
[11:31:50 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'speed' in plugin EssentialsP v1.2.3-beta.1
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:942) ~[purpur-1.19.2.jar:git-Purpur-1775]
	at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[purpur-1.19.2.jar:git-Purpur-1775]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[purpur-1.19.2.jar:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:311) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:295) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2384) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$21(ServerGamePacketListenerImpl.java:2338) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.2.jar:git-Purpur-1775]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1388) ~[purpur-1.19.2.jar:git-Purpur-1775]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[purpur-1.19.2.jar:git-Purpur-1775]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1365) ~[purpur-1.19.2.jar:git-Purpur-1775]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1358) ~[purpur-1.19.2.jar:git-Purpur-1775]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1492) ~[purpur-1.19.2.jar:git-Purpur-1775]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[purpur-1.19.2.jar:git-Purpur-1775]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1775]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NumberFormatException: For input string: "1.3000aaaaaaa"
	at jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054) ~[?:?]
	at jdk.internal.math.FloatingDecimal.parseFloat(FloatingDecimal.java:122) ~[?:?]
	at java.lang.Float.parseFloat(Float.java:476) ~[?:?]
	at tk.pandadev.essentialsp.commands.SpeedCommand.onCommand(SpeedCommand.java:23) ~[EssentialsP-1.2.3-beta.1.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	... 23 more
```

Doing `/rank` with no arguments creates an unhandled exception
```console
[11:33:32 INFO]: _Rhythmic issued server command: /rank
[11:33:32 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'rank' in plugin EssentialsP v1.2.3-beta.1
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:942) ~[purpur-1.19.2.jar:git-Purpur-1775]
	at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[purpur-1.19.2.jar:git-Purpur-1775]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[purpur-1.19.2.jar:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:311) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:295) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2384) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$21(ServerGamePacketListenerImpl.java:2338) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.2.jar:git-Purpur-1775]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1388) ~[purpur-1.19.2.jar:git-Purpur-1775]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[purpur-1.19.2.jar:git-Purpur-1775]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1365) ~[purpur-1.19.2.jar:git-Purpur-1775]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1358) ~[purpur-1.19.2.jar:git-Purpur-1775]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1336) ~[purpur-1.19.2.jar:git-Purpur-1775]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1224) ~[purpur-1.19.2.jar:git-Purpur-1775]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1775]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at tk.pandadev.essentialsp.commands.RankCommand.onCommand(RankCommand.java:30) ~[EssentialsP-1.2.3-beta.1.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	... 23 more
```
doing `/rank modify` also
```console
[11:36:34 INFO]: _Rhythmic issued server command: /rank modify
[11:36:34 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'rank' in plugin EssentialsP v1.2.3-beta.1
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:942) ~[purpur-1.19.2.jar:git-Purpur-1775]
	at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[purpur-1.19.2.jar:git-Purpur-1775]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[purpur-1.19.2.jar:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:311) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:295) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2384) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$21(ServerGamePacketListenerImpl.java:2338) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.2.jar:git-Purpur-1775]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1388) ~[purpur-1.19.2.jar:git-Purpur-1775]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[purpur-1.19.2.jar:git-Purpur-1775]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1365) ~[purpur-1.19.2.jar:git-Purpur-1775]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1358) ~[purpur-1.19.2.jar:git-Purpur-1775]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1336) ~[purpur-1.19.2.jar:git-Purpur-1775]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1224) ~[purpur-1.19.2.jar:git-Purpur-1775]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1775]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at tk.pandadev.essentialsp.commands.RankCommand.onCommand(RankCommand.java:93) ~[EssentialsP-1.2.3-beta.1.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	... 23 more
```
doing `/rank create` provides this 
![image](https://user-images.githubusercontent.com/45906780/189421011-bd3adff5-d1d3-4630-8bcb-ae7667c85c1d.png)
which doesn't appear to be accurate

Clearing someone's rank does not clear their tab name
![image](https://user-images.githubusercontent.com/45906780/189421267-3ccc41ad-2125-43dd-8b94-7ee4d3d4ea75.png)


Name/Prefix persist after the plugin and plugin folder has been removed

![image](https://user-images.githubusercontent.com/45906780/189421490-33769f4f-cded-4703-b527-bf4c61683c03.png)
![image](https://user-images.githubusercontent.com/45906780/189421546-4fe6ee1b-c937-4bd3-9010-991784c07bf8.png)

Startup log for that session: 

```console
rhythmic@rhythmic:/media/rhythmic/9217a4fc-6348-4930-89f3-1e58ba8fdd9d/test server$ bash start.sh
WARNING: Using incubator modules: jdk.incubator.vector
Starting org.bukkit.craftbukkit.Main
System Info: Java 17 (Java HotSpot(TM) 64-Bit Server VM 17.0.4+11-LTS-179) Host: Linux 5.15.0-47-generic (amd64)
Loading libraries, please wait...
[11:40:59 INFO]: Building unoptimized datafixer
[11:41:00 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[11:41:02 INFO]: Loaded 7 recipes
[11:41:03 INFO]: Starting minecraft server version 1.19.2
[11:41:03 INFO]: Loading properties
[11:41:03 INFO]: This server is running Purpur version git-Purpur-1775 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 6dc65d2 on HEAD)
[11:41:03 INFO]: Server Ping Player Sample Count: 12
[11:41:03 INFO]: Using 4 threads for Netty based IO
[11:41:04 INFO]: [Pufferfish] Max SIMD vector size on this system is 256 bits (int)
[11:41:04 INFO]: [Pufferfish] Max SIMD vector size on this system is 256 bits (float)
[11:41:04 INFO]: [Pufferfish] SIMD operations detected as functional. Will replace some operations with faster versions.
[11:41:04 INFO]: Default game type: SURVIVAL
[11:41:04 INFO]: Generating keypair
[11:41:04 INFO]: Starting Minecraft server on *:25565
[11:41:04 INFO]: Using epoll channel type
[11:41:04 INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
[11:41:04 INFO]: Paper: Using Java cipher from Velocity.
[11:41:06 INFO]: [spark] Loading spark v1.9.36
[11:41:06 INFO]: Server permissions file permissions.yml is empty, ignoring it
[11:41:06 INFO]: Preparing level "world"
[11:41:06 INFO]: Preparing start region for dimension minecraft:overworld
[11:41:07 INFO]: Time elapsed: 299 ms
[11:41:07 INFO]: Preparing start region for dimension minecraft:the_nether
[11:41:07 INFO]: Time elapsed: 68 ms
[11:41:07 INFO]: Preparing start region for dimension minecraft:the_end
[11:41:07 INFO]: Time elapsed: 64 ms
[11:41:07 INFO]: [spark] Enabling spark v1.9.36
[11:41:07 INFO]: [spark] Using Paper ServerTickStartEvent for tick monitoring
[11:41:08 INFO]: Running delayed init tasks
[11:41:08 INFO]: Done (4.575s)! For help, type "help"
[11:41:15 INFO]: UUID of player _Rhythmic is f899e56c-f741-4a92-a3d8-ee6f9ef05546
[11:41:15 INFO]: Player • _Rhythmic joined the game
[11:41:15 INFO]: _Rhythmic[/[0:0:0:0:0:0:0:1%0]:52268] logged in with entity id 117 at ([world]-80.4819844267694, 35.86859856141189, -89.63944074588993)
> 
```

**Comment by 0PandaDEV** [comment]
Thanks for your analysis a few bugs I already found and fixed myself but most not if you want to stay up to date you can always download the latest beta on [Modrinth ](https://modrinth.com/plugin/essentialsp) or [GitHub releases](https://github.com/0PandaDEV/EssentialsP/releases)
